pipeline{
    agent{
        label "node"
    }
    stages{
        stage("build"){
            
            tools {
            go 'golang 1.18.1'
            }

            steps{
                echo "========Building Go app========"
                sh "env GOOS=linux GOARCH=arm64 go build main.go"
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}